### ISSUE TITLE
Consolidate arduino.py files

### ISSUE THREAD

**Issue by abe-mart** [APMonitor/arduino#3]
It would be nice to combine the arduino.py files into a single file that is referenced in each sub module.

**Comment by jckantor** [comment]
Agreed.  I'm contemplating how to add some jupyter notebooks to the repo, and am considering a new folder labeled 'notebooks' that would then import arduino.py   For this purpose, I'd suggest a new top-level folder labeled 'lib'  to hold arduino, then import from there for all other uses.  Does that make sense?

**Comment by APMonitor** [comment]
The arduino.py file is removed and the package is replaced by tclab that is now available from 'pip install tclab'.
