### ISSUE TITLE
Arduino() doesn't find port on MacOS

### ISSUE THREAD

**Issue by jckantor** [APMonitor/arduino#6]
@APMonitor I'm testing with MacOS X (High Sierra) and Python 3.6 (Anaconda distribution).  serial.tools.list_ports.comports() doesn't return a list of active ports, therefore Arduino.findport() fails.  

One fix, not pretty, would be an optional argument to Arduino() to specify a port.  If a port was specified, then findPort() wouldn't need to be called.  The placeholder is already there, just need to modify the logic in __init__

**Comment by alchemyst** [comment]
I had issues with the drivers on my computer, solved by installing [these drivers](https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver).

**Comment by APMonitor** [comment]
Thanks for pointing to these drivers for MacOS. I've included a number of other initial setup and configuration tips here http://apmonitor.com/pdc/index.php/Main/ArduinoSetup

**Comment by APMonitor** [comment]
One user reported that they don't want to install an additional driver on MacOS, citing a concern about the source of the driver. This user said that they overcame the driver issue by connecting a Raspberry Pi (Linux) to control the device. I suppose this is an option but still not optimal for MacOS users. The Windows and Linux experience seems much easier with respect to drivers. Any additional thoughts on this issue? Should the Hduino Uno be replaced with a different version for MacOS users to help with the driver issue?

**Comment by alchemyst** [comment]
I don't see any reason to doubt the validity of the drivers we link to in the README. They work perfectly for all the students and myself who use them with the Mac. I've had much more problems with Windows users with my units. It appears that the real problem is not so much the platform as the specific chips (CH34x).

**Comment by jckantor** [comment]
I've been having good luck with the Leonardo which doesn't require a new
driver for the Mac.  The only issue is that Leonardo creates a new com port
on each invocation of TCLab.  So I agree with Carl, that the Mac with CH34x
driver is actually the more consistently reliable platform.  We only had a
couple of macs (out of perhaps 40 or so) with stubborn problems.  For those
we substituted Leonardos as a fix.

The hard problems have been recalcitrant Windows machines that, for some
reason, just don't want to connect.  Our experience is that if we can
connect with the Arduino IDE then we're good to go with the TC lab.  We
have a few that just haven't worked.  It's hard to identify a particular
pattern to the problem.

The NHduino is definitely faster than Leonardo.  We get about 40 samples
per second on NHduino vs 12-15 with Leonardo using the TCLab-sketch.  I
haven't benchmarked Firmata and am curious how that would compare.

John ... we'll finish the substitution of Leonardos for NHDuinos over
Spring break, and the unused units back to you.

Jeff

**Comment by APMonitor** [comment]
We switched to Arduino Leonardos to resolve the driver concern. The TCLab now works on Linux, MacOS, and Windows without driver issues.
